# Generated by Django 5.0.2 on 2024-02-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("setNo", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("img", models.ImageField(upload_to="")),
                ("country", models.CharField(max_length=200)),
                ("prev_team", models.CharField(max_length=5)),
                ("basePrice", models.PositiveIntegerField()),
                ("age", models.PositiveSmallIntegerField()),
                ("numMatches", models.PositiveIntegerField()),
                ("numRuns", models.PositiveIntegerField(blank=True, null=True)),
                ("battingAvg", models.FloatField(blank=True, null=True)),
                ("strikeRate", models.FloatField(blank=True, null=True)),
                ("numWickets", models.PositiveIntegerField(blank=True, null=True)),
                ("bowlingAvg", models.FloatField(blank=True, null=True)),
                ("bowlingEconomy", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
