# Generated by Django 5.0.2 on 2024-02-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="prev_team",
            field=models.CharField(max_length=4),
        ),
    ]
