# Generated by Django 5.0.2 on 2024-03-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_prev_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="numMatches",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
